version: "3"

services:
  micro_agent:
    build: .
    container_name: micro_agent
    cap_add:
      - NET_ADMIN
    network_mode: host
    ports:
      - "8010:8010"
      - "8000:8000"
      - "2222:22"
    volumes:
      - .:/app
    stdin_open: true # 保持标准输入开启
    tty: true # 分配伪终端
    restart: unless-stopped
